name: PR Build

on: [pull_request]

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Patch Lamius
        run: |
          git submodule update --init --recursive
          ./Lamius jar

      - uses: actions/upload-artifact@v2
        with:
          name: Lamius-PR${{ github.event.pull_request.number }}-JDK8
          path: Lamius-paperclip.jar